### ISSUE TITLE
Stop Pagination 

### ISSUE THREAD

**Issue by engWaleed** [fedefrappi/AePubReader#17]
how can we stop the pagination before it ends by it self ?

**Comment by tuantmdev** [comment]
Just create a variable and mark it as you want (BOOL wantToStop = YES) and check it in Chapter delegate. If YES, stop loading next chapter.

**Comment by engWaleed** [comment]
thank you very much , you set me on the right place , i did put a flag , and it get checked b4 starting a new chapter , if it is to be stopped i don't start paginating the next one ..
