### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by larrymail2011** [fedefrappi/AePubReader#4]
What is the AePubReader's license?

Thanks
Larry

**Comment by fedefrappi** [comment]
Hi Larry,
We haven't really thought about licensing, you can use it freely. A thank you line somewhere in your app would be appreciated anyway and we would be thrilled if you let us know when you are shipping your app ;)

Thanks,
Federico

**Comment by larrymail2011** [comment]
Hi Federico,

I will definitely have a thank you line in my ebook app. I will submitted it to apple store in next couple days and let you know when it is available in app store.

Thank you very much!
Larry

**Comment by matteinn** [comment]
Hi Larry,
we're glad our code has been useful. Good luck!

**Comment by larrymail2011** [comment]
Hi Federico,

I submitted my book yesterday to app store and it is really nice if the
book app can be available on iPhone,
I wonder if AePubReader  has iPhone version.

Thank you very much! Merry Christmas!

Larry

On Sat, Dec 24, 2011 at 8:35 AM, matteinn <
reply@reply.github.com

**Comment by fedefrappi** [comment]
Hi Larry, I hope you had a great Christmas ;)
There is no iPhone version of AePubReader, if you want to make an universal app from it you should make a new iphone specific nib and avoid the popupcontrollers which aren't available on the iphone.

Bye,
Federico

**Comment by larrymail2011** [comment]
Hi Federico,

Thanks for your suggestions. Happy new years!

Larry

On Wed, Jan 4, 2012 at 10:31 AM, Federico Frappi <
reply@reply.github.com

**Comment by almostabc** [comment]
Hi Frederico,

Thanks so much for providing this code. Just to clarify on your comment above, are we free to use this for commercial purposes? Happy to a mention in the app.

Thanks,
Andrew

**Comment by fedefrappi** [comment]
Hi Andrew, 

Yes, you can use this code for commercial purposes.

**Comment by dineshprasanna** [comment]
Hi Frederico,
                   I am also developing the ebook app but i totally strucked in the landscape part could you help me
